### ISSUE TITLE
Unable to obtain the script using 'malior install malior-redroid'

### ISSUE THREAD

**Issue by LiuTangLei** [ChisBread/malior#9]
In the terminal log, it can be seen that this command will go to https://github.com/ChisBread/malior/raw/main/docker/malior-redroid-install.sh to obtain the installation script. However, it has been found that the installation script is no longer available in the repository.

**Comment by KingingWang** [comment]
me too

**Comment by KingingWang** [comment]
我已经配置完成,安装脚本貌似出现了一些问题,稍微修改一下即可,我稍后整理一下

**Comment by LiuTangLei** [comment]
issue resolved，thanks
